version: "3.3"
services:
    app:
        image: php7.4-fpm
        container_name: fpm
        volumes:
            - ./:/var/www/ 
    nginx:
        image: nginx
        container_name: nginx
        ports: 
            - 8000:80
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
            - ./:/var/www/
        depends_on:
            -  app